const COLORS = {
    BLACK: "#000000",
    BORDER: "#E0E0E0",
    BLUE_DARK: "#126EBE",
    BLUE_LIGHT: "#CFE4FA",
    GRAY_DARK: "#7E7E7E",
    GRAY_LIGHT: "#F5F5F5",
    GRAY_LIGHT2: "#F0F0F0",
    GRAY_MEDIUM: "#C2C2C2",
    GREEN: "#31de57",
    ORANGE: "#FC4C02",
    PINK: "#FF4B6B",
    PRIMARY: "#000000",
    PURPLE: "#9D00FF",
    RED: "#FF0000",
    SECONDARY: "#666666",
    SIDEBAR: "#F5F5F5BB",
    TERTIARY: "#AAAAAA",
    TRANSPARENT: "transparent",
    WHITE: "#FFFFFF",
    YELLOW: "gold",
};

export const CATEGORY_COLORS = [
    COLORS.RED,
    COLORS.ORANGE,
    COLORS.YELLOW,
    COLORS.GREEN,
    COLORS.BLUE_DARK,
    COLORS.BLUE_LIGHT,
    COLORS.PINK,
    COLORS.PURPLE,
    COLORS.GRAY_MEDIUM,
];

export default COLORS;
