const HEADER_HEIGHT = 90;
const HOME_PADDING = 30;

const DIMENS = {
    AVATAR_SIZE: 30,
    BUTTON_HEIGHT: 32,
    BUTTON_WIDTH: 85,
    EMAIL_HEIGHT: 64,
    EMAIL_LIST_HEIGHT: `calc(100vh - ${HOME_PADDING}px - ${HEADER_HEIGHT}px - 15px)`,
    EMAIL_WIDTH: 300,
    HEADER_HEIGHT: HEADER_HEIGHT,
    HEADER_SECTION_HEIGHT: HEADER_HEIGHT - 30,
    HOME_PADDING: HOME_PADDING,
    NAVBAR_HEIGHT: 50,
    SELECT_WIDTH: 80,
    SIDEBAR_WIDTH: 50,
    SPACING_STANDARD: 10,
};

export default DIMENS;
