const HEADER_HEIGHT = 100;
const HOME_PADDING = 30;

const DIMENS = {
    AVATAR_SIZE: 30,
    BUTTON_HEIGHT: 32,
    BUTTON_WIDTH: 75,
    EMAIL_HEIGHT: 64,
    EMAIL_LIST_HEIGHT: `calc(100vh - ${HOME_PADDING}px - ${HEADER_HEIGHT}px - 30px)`,
    EMAIL_WIDTH: 300,
    HEADER_HEIGHT: HEADER_HEIGHT,
    HOME_PADDING: HOME_PADDING,
    SPACING_STANDARD: 10,
};

export default DIMENS;
