import {} from "@mdi/js";

import {
    FaAtom,
    FaBars,
    FaCalendarAlt,
    FaCheck,
    FaCloud,
    FaEnvelopeOpenText,
    FaFileAlt,
    FaFolder,
    FaInbox,
    FaRegEnvelope,
    FaRegFolder,
    FaRegTrashAlt,
    FaSign,
    FaSitemap,
    FaStroopwafel,
    FaTag,
    FaTh,
    FaUser,
    FaUserFriends,
} from "react-icons/fa";

export const ICON = {
    CALENDAR: "CALENDAR",
    CATEGORY: "CATEGORY",
    CHECK: "CHECK",
    CLOUD: "CLOUD",
    ENVELOPE: "ENVELOPE",
    FOLDER: "FOLDER",
    FOLDER_REG: "FOLDER_REG",
    INBOX: "INBOX",
    LABEL: "LABEL",
    MAIL: "MAIL",
    MENU: "MENU",
    NEWS: "NEWS",
    NETWORK: "NETWORK",
    RUN: "RUN",
    SENDER: "SENDER",
    STROOP: "STROOP",
    TABLE: "TABLE",
    TRASH: "TRASH",
    USERS: "USERS",
};

export const FA_COMPONENTS = {
    [ICON.CALENDAR]: FaCalendarAlt,
    [ICON.CATEGORY]: FaTag,
    [ICON.CHECK]: FaCheck,
    [ICON.CLOUD]: FaCloud,
    [ICON.ENVELOPE]: FaRegEnvelope,
    [ICON.FOLDER]: FaFolder,
    [ICON.FOLDER_REG]: FaRegFolder,
    [ICON.INBOX]: FaInbox,
    [ICON.LABEL]: FaSign,
    [ICON.MAIL]: FaEnvelopeOpenText,
    [ICON.MENU]: FaBars,
    [ICON.NETWORK]: FaSitemap,
    [ICON.NEWS]: FaFileAlt,
    [ICON.RUN]: FaAtom,
    [ICON.SENDER]: FaUser,
    [ICON.STROOP]: FaStroopwafel,
    [ICON.TABLE]: FaTh,
    [ICON.TRASH]: FaRegTrashAlt,
    [ICON.USERS]: FaUserFriends,
};

export const MDI_COMPONENTS = {};
