import {
    FaAtom,
    FaBan,
    FaBars,
    FaBraille,
    FaBrain,
    FaCalendarAlt,
    FaCalendarDay,
    FaCheck,
    FaCloud,
    FaEnvelopeOpenText,
    FaEnvelopeSquare,
    FaFileAlt,
    FaFolder,
    FaInbox,
    FaKey,
    FaKickstarterK,
    FaMarker,
    FaRegEnvelope,
    FaRegFolder,
    FaRegTrashAlt,
    FaSign,
    FaSitemap,
    FaStroopwafel,
    FaTag,
    FaTh,
    FaUser,
    FaUserFriends,
} from "react-icons/fa";

export const ICON = {
    BAN: "BAN",
    CALENDAR: "CALENDAR",
    CATEGORY: "CATEGORY",
    CHART: "CHART",
    CHECK: "CHECK",
    CLOUD: "CLOUD",
    DATE: "DATE",
    ENVELOPE: "ENVELOPE",
    FOLDER: "FOLDER",
    FOLDER_REG: "FOLDER_REG",
    HDBSCAN: "HDBSCAN",
    INBOX: "INBOX",
    KEY: "KEY",
    KMEANS: "KMEANS",
    LABEL: "LABEL",
    MAIL: "MAIL",
    MENU: "MENU",
    NEWS: "NEWS",
    NETWORK: "NETWORK",
    RUN: "RUN",
    SENDER: "SENDER",
    STROOP: "STROOP",
    SUBJECT: "SUBJECT",
    TABLE: "TABLE",
    THREAD_ID: "THREAD_ID",
    TRASH: "TRASH",
    USERS: "USERS",
};

export const FA_COMPONENTS = {
    [ICON.BAN]: FaBan,
    [ICON.CALENDAR]: FaCalendarAlt,
    [ICON.CATEGORY]: FaTag,
    [ICON.CHART]: FaBraille,
    [ICON.CHECK]: FaCheck,
    [ICON.CLOUD]: FaCloud,
    [ICON.DATE]: FaCalendarDay,
    [ICON.ENVELOPE]: FaRegEnvelope,
    [ICON.FOLDER]: FaFolder,
    [ICON.FOLDER_REG]: FaRegFolder,
    [ICON.HDBSCAN]: FaBrain,
    [ICON.INBOX]: FaInbox,
    [ICON.KEY]: FaKey,
    [ICON.KMEANS]: FaKickstarterK,
    [ICON.LABEL]: FaSign,
    [ICON.MAIL]: FaEnvelopeOpenText,
    [ICON.MENU]: FaBars,
    [ICON.NETWORK]: FaSitemap,
    [ICON.NEWS]: FaFileAlt,
    [ICON.RUN]: FaAtom,
    [ICON.SENDER]: FaUser,
    [ICON.STROOP]: FaStroopwafel,
    [ICON.SUBJECT]: FaMarker,
    [ICON.TABLE]: FaTh,
    [ICON.THREAD_ID]: FaEnvelopeSquare,
    [ICON.TRASH]: FaRegTrashAlt,
    [ICON.USERS]: FaUserFriends,
};
