import {
    FaAtom,
    FaBan,
    FaBars,
    FaBraille,
    FaBrain,
    FaCalendarAlt,
    FaCalendarDay,
    FaChartBar,
    FaChartLine,
    FaCheck,
    FaChevronDown,
    FaCloud,
    FaEnvelopeOpenText,
    FaEnvelopeSquare,
    FaExclamationTriangle,
    FaFileAlt,
    FaFolder,
    FaFont,
    FaHistory,
    FaInbox,
    FaKey,
    FaKickstarterK,
    FaMarker,
    FaRegEnvelope,
    FaRegFileAlt,
    FaRegFolder,
    FaRegTrashAlt,
    FaSign,
    FaSignOutAlt,
    FaSitemap,
    FaSortAlphaDown,
    FaStroopwafel,
    FaTag,
    FaTh,
    FaTimes,
    FaUser,
    FaUserFriends,
} from "react-icons/fa";

export const ICON = {
    BAN: "BAN",
    BAR_CHART: "BAR_CHART",
    BODY: "BODY",
    CALENDAR: "CALENDAR",
    CAPITALS: "CAPITALS",
    CATEGORY: "CATEGORY",
    CHART: "CHART",
    CHECK: "CHECK",
    CHEV_DOWN: "CHEV_DOWN",
    CLOSE: "CLOSE",
    CLOUD: "CLOUD",
    DATE: "DATE",
    ELBOW: "ELBOW",
    ENVELOPE: "ENVELOPE",
    FOLDER: "FOLDER",
    FOLDER_REG: "FOLDER_REG",
    HDBSCAN: "HDBSCAN",
    HISTORY: "HISTORY",
    INBOX: "INBOX",
    KEY: "KEY",
    KMEANS: "KMEANS",
    LABEL: "LABEL",
    LOGOUT: "LOGOUT",
    MAIL: "MAIL",
    MENU: "MENU",
    NEWS: "NEWS",
    NETWORK: "NETWORK",
    RUN: "RUN",
    SENDER: "SENDER",
    SORT: "SORT",
    STOPWORDS: "STOPWORDS",
    STROOP: "STROOP",
    SUBJECT: "SUBJECT",
    TABLE: "TABLE",
    THREAD_ID: "THREAD_ID",
    TRASH: "TRASH",
    USERS: "USERS",
    WARNING: "WARNING",
};

export const FA_COMPONENTS = {
    [ICON.BAN]: FaBan,
    [ICON.BAR_CHART]: FaChartBar,
    [ICON.BODY]: FaRegFileAlt,
    [ICON.CALENDAR]: FaCalendarAlt,
    [ICON.CAPITALS]: FaFont,
    [ICON.CATEGORY]: FaTag,
    [ICON.CHART]: FaBraille,
    [ICON.CHECK]: FaCheck,
    [ICON.CHEV_DOWN]: FaChevronDown,
    [ICON.CLOSE]: FaTimes,
    [ICON.CLOUD]: FaCloud,
    [ICON.DATE]: FaCalendarDay,
    [ICON.ELBOW]: FaChartLine,
    [ICON.ENVELOPE]: FaRegEnvelope,
    [ICON.FOLDER]: FaFolder,
    [ICON.FOLDER_REG]: FaRegFolder,
    [ICON.HDBSCAN]: FaBrain,
    [ICON.HISTORY]: FaHistory,
    [ICON.INBOX]: FaInbox,
    [ICON.KEY]: FaKey,
    [ICON.KMEANS]: FaKickstarterK,
    [ICON.LABEL]: FaSign,
    [ICON.LOGOUT]: FaSignOutAlt,
    [ICON.MAIL]: FaEnvelopeOpenText,
    [ICON.MENU]: FaBars,
    [ICON.NETWORK]: FaSitemap,
    [ICON.NEWS]: FaFileAlt,
    [ICON.RUN]: FaAtom,
    [ICON.SENDER]: FaUser,
    [ICON.SORT]: FaSortAlphaDown,
    [ICON.STOPWORDS]: FaBan,
    [ICON.STROOP]: FaStroopwafel,
    [ICON.SUBJECT]: FaMarker,
    [ICON.TABLE]: FaTh,
    [ICON.THREAD_ID]: FaEnvelopeSquare,
    [ICON.TRASH]: FaRegTrashAlt,
    [ICON.USERS]: FaUserFriends,
    [ICON.WARNING]: FaExclamationTriangle,
};
